"""fix enum values for evaluationtype and userrole

Revision ID: 51b38b07f78f
Revises: b9c2f0f7a3c1
Create Date: 2026-05-11 17:41:11.093166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '51b38b07f78f'
down_revision: Union[str, None] = 'b9c2f0f7a3c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'cv_evaluations', ['evaluation_id'])
    op.drop_constraint('cv_evaluations_ibfk_1', 'cv_evaluations', type_='foreignkey')
    op.create_foreign_key(None, 'cv_evaluations', 'evaluations', ['evaluation_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'english_evaluations', ['evaluation_id'])
    op.drop_constraint('english_evaluations_ibfk_1', 'english_evaluations', type_='foreignkey')
    op.create_foreign_key(None, 'english_evaluations', 'evaluations', ['evaluation_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_evaluation_notes_id'), 'evaluation_notes', ['id'], unique=False)
    op.create_index('ix_evaluations_user_type_created', 'evaluations', ['user_id', 'evaluation_type', 'created_at'], unique=False)
    op.create_index('ix_evaluations_user_type_status', 'evaluations', ['user_id', 'evaluation_type', 'status'], unique=False)
    op.drop_constraint('evaluations_ibfk_1', 'evaluations', type_='foreignkey')
    op.create_foreign_key(None, 'evaluations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'github_evaluations', ['evaluation_id'])
    op.drop_constraint('github_evaluations_ibfk_1', 'github_evaluations', type_='foreignkey')
    op.create_foreign_key(None, 'github_evaluations', 'evaluations', ['evaluation_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'idea_evaluations', ['evaluation_id'])
    op.drop_constraint('idea_evaluations_ibfk_1', 'idea_evaluations', type_='foreignkey')
    op.create_foreign_key(None, 'idea_evaluations', 'evaluations', ['evaluation_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'interview_evaluations', ['evaluation_id'])
    op.drop_constraint('interview_evaluations_ibfk_1', 'interview_evaluations', type_='foreignkey')
    op.create_foreign_key(None, 'interview_evaluations', 'evaluations', ['evaluation_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'linkedin_evaluations', ['evaluation_id'])
    op.drop_constraint('linkedin_evaluations_ibfk_1', 'linkedin_evaluations', type_='foreignkey')
    op.create_foreign_key(None, 'linkedin_evaluations', 'evaluations', ['evaluation_id'], ['id'], ondelete='CASCADE')
    op.alter_column('readiness_scores', 'cv_completed',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Boolean(),
               nullable=False)
    op.alter_column('readiness_scores', 'github_completed',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Boolean(),
               nullable=False)
    op.alter_column('readiness_scores', 'linkedin_completed',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Boolean(),
               nullable=False)
    op.alter_column('readiness_scores', 'idea_completed',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Boolean(),
               nullable=False)
    op.alter_column('readiness_scores', 'interview_completed',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Boolean(),
               nullable=False)
    op.alter_column('readiness_scores', 'english_completed',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Boolean(),
               nullable=False)
    op.drop_constraint('readiness_scores_ibfk_1', 'readiness_scores', type_='foreignkey')
    op.create_foreign_key(None, 'readiness_scores', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_users_instructor_id'), 'users', ['instructor_id'], unique=False)
    op.drop_constraint('users_ibfk_1', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'users', ['instructor_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_ibfk_1', 'users', 'users', ['instructor_id'], ['id'])
    op.drop_index(op.f('ix_users_instructor_id'), table_name='users')
    op.drop_constraint(None, 'readiness_scores', type_='foreignkey')
    op.create_foreign_key('readiness_scores_ibfk_1', 'readiness_scores', 'users', ['user_id'], ['id'])
    op.alter_column('readiness_scores', 'english_completed',
               existing_type=sa.Boolean(),
               type_=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('readiness_scores', 'interview_completed',
               existing_type=sa.Boolean(),
               type_=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('readiness_scores', 'idea_completed',
               existing_type=sa.Boolean(),
               type_=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('readiness_scores', 'linkedin_completed',
               existing_type=sa.Boolean(),
               type_=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('readiness_scores', 'github_completed',
               existing_type=sa.Boolean(),
               type_=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('readiness_scores', 'cv_completed',
               existing_type=sa.Boolean(),
               type_=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_constraint(None, 'linkedin_evaluations', type_='foreignkey')
    op.create_foreign_key('linkedin_evaluations_ibfk_1', 'linkedin_evaluations', 'evaluations', ['evaluation_id'], ['id'])
    op.drop_constraint(None, 'linkedin_evaluations', type_='unique')
    op.drop_constraint(None, 'interview_evaluations', type_='foreignkey')
    op.create_foreign_key('interview_evaluations_ibfk_1', 'interview_evaluations', 'evaluations', ['evaluation_id'], ['id'])
    op.drop_constraint(None, 'interview_evaluations', type_='unique')
    op.drop_constraint(None, 'idea_evaluations', type_='foreignkey')
    op.create_foreign_key('idea_evaluations_ibfk_1', 'idea_evaluations', 'evaluations', ['evaluation_id'], ['id'])
    op.drop_constraint(None, 'idea_evaluations', type_='unique')
    op.drop_constraint(None, 'github_evaluations', type_='foreignkey')
    op.create_foreign_key('github_evaluations_ibfk_1', 'github_evaluations', 'evaluations', ['evaluation_id'], ['id'])
    op.drop_constraint(None, 'github_evaluations', type_='unique')
    op.drop_constraint(None, 'evaluations', type_='foreignkey')
    op.create_foreign_key('evaluations_ibfk_1', 'evaluations', 'users', ['user_id'], ['id'])
    op.drop_index('ix_evaluations_user_type_status', table_name='evaluations')
    op.drop_index('ix_evaluations_user_type_created', table_name='evaluations')
    op.drop_index(op.f('ix_evaluation_notes_id'), table_name='evaluation_notes')
    op.drop_constraint(None, 'english_evaluations', type_='foreignkey')
    op.create_foreign_key('english_evaluations_ibfk_1', 'english_evaluations', 'evaluations', ['evaluation_id'], ['id'])
    op.drop_constraint(None, 'english_evaluations', type_='unique')
    op.drop_constraint(None, 'cv_evaluations', type_='foreignkey')
    op.create_foreign_key('cv_evaluations_ibfk_1', 'cv_evaluations', 'evaluations', ['evaluation_id'], ['id'])
    op.drop_constraint(None, 'cv_evaluations', type_='unique')
    # ### end Alembic commands ###
